import { useEffect, useMemo, useState } from "react";
import { procurementFiscalControlApi, type FiscalDocument, type FiscalFacts, type PaymentRequest, type ReconciliationView } from "../api/procurementFiscalControl";
import { useAuth } from "../auth/AuthContext";

function today() { return new Date().toISOString().slice(0, 10); }
function money(value: number, currency: string) { return new Intl.NumberFormat("pt-MZ", { style: "currency", currency, maximumFractionDigits: 2 }).format(value); }
const emptyFacts: FiscalFacts = {};

export default function ProcurementFiscalControlPanel({ projectId, invoiceId, invoiceStatus, outstanding, currency, canApprove, onChanged }: { projectId: string; invoiceId: string; invoiceStatus: string; outstanding: number; currency: string; canApprove: boolean; onChanged?: () => void }) {
  const { user } = useAuth(); const isFinanceAdmin = user?.role === "admin_empresa" || user?.role === "super_admin";
  const [docs, setDocs] = useState<FiscalDocument[]>([]); const [payments, setPayments] = useState<PaymentRequest[]>([]); const [bank, setBank] = useState<ReconciliationView | null>(null); const [facts, setFacts] = useState<FiscalFacts>({ ...emptyFacts, currency: currency === "USD" ? "USD" : "MZN" }); const [selectedDocId, setSelectedDocId] = useState<string | null>(null);
  const [amount, setAmount] = useState(outstanding > 0 ? String(outstanding) : ""); const [manualMatch, setManualMatch] = useState<Record<string,string>>({}); const [paymentDate, setPaymentDate] = useState(today()); const [reason, setReason] = useState("Pagamento da factura validada"); const [overrideReason, setOverrideReason] = useState(""); const [executionRef, setExecutionRef] = useState(""); const [error, setError] = useState<string | null>(null); const [busy, setBusy] = useState(false); const [bankOpen, setBankOpen] = useState(false); const [bankName, setBankName] = useState("");
  async function reload() { const [fiscalRows, paymentRows] = await Promise.all([procurementFiscalControlApi.fiscalDocuments(invoiceId), procurementFiscalControlApi.paymentRequests(invoiceId)]); setDocs(fiscalRows); setPayments(paymentRows); const preferred = fiscalRows.find((doc) => doc.id === selectedDocId) ?? fiscalRows[0]; if (preferred) { setSelectedDocId(preferred.id); setFacts({ currency: currency === "USD" ? "USD" : "MZN", ...((preferred.reviewedData ?? preferred.extractedData ?? {}) as FiscalFacts) }); } if (bankOpen) setBank(await procurementFiscalControlApi.bankReconciliation(projectId)); }
  useEffect(() => { void reload().catch((cause) => setError(cause instanceof Error ? cause.message : "Erro fiscal")); }, [invoiceId]);
  const selectedDoc = docs.find((doc) => doc.id === selectedDocId) ?? null; const latestDoc = docs[0] ?? null; const hasValidated = latestDoc?.status === "validado"; const activeReserved = useMemo(() => payments.filter((p) => p.status === "aprovado").reduce((sum,p) => sum + Number(p.amount),0), [payments]);
  async function run(task: () => Promise<unknown>) { setBusy(true); setError(null); try { await task(); await reload(); onChanged?.(); } catch (cause) { setError(cause instanceof Error ? cause.message : "Operação não concluída"); } finally { setBusy(false); } }
  return <div className="space-y-4 rounded-xl border border-slate-200 p-4">
    <div><h4 className="font-semibold text-sm">Documento fiscal e controlo de pagamento</h4><p className="text-xs text-slate-500">O ficheiro original é hashado. OCR/IA apenas propõe dados; a validação é humana.</p></div>{error && <p className="rounded-lg bg-red-50 px-3 py-2 text-xs text-red-700">{error}</p>}
    <section className="rounded-xl bg-slate-50 p-3 space-y-3"><div className="flex flex-wrap justify-between gap-2"><div><strong className="text-sm">1. Documento fiscal</strong><p className="text-xs text-slate-500">Obrigatório antes da aprovação da factura.</p></div><label className="btn cursor-pointer">Carregar PDF/imagem<input type="file" accept="application/pdf,image/*" className="hidden" onChange={(e) => { const file=e.target.files?.[0]; if(file) void run(() => procurementFiscalControlApi.uploadFiscal(invoiceId,file)); }}/></label></div>
      {docs.length === 0 ? <p className="text-xs text-amber-700">Documento fiscal ainda não carregado.</p> : <div className="space-y-2">{docs.map((doc) => <button key={doc.id} className={`w-full rounded-lg border px-3 py-2 text-left text-xs ${doc.id===selectedDocId?"border-sigo-teal bg-white":"border-slate-200"}`} onClick={() => { setSelectedDocId(doc.id); setFacts({ currency: currency === "USD" ? "USD" : "MZN", ...((doc.reviewedData ?? doc.extractedData ?? {}) as FiscalFacts) }); }}><strong>v{doc.version} · {doc.originalName}</strong><span className="ml-2">{doc.status.replaceAll("_"," ")}</span><p className="text-slate-500">SHA-256 {doc.sha256.slice(0,16)}… {doc.extractionProvider ? `· ${doc.extractionProvider}`:""}</p></button>)}</div>}
      {selectedDoc && <><div className="flex flex-wrap gap-2"><a className="btn" href={procurementFiscalControlApi.fiscalFileUrl(selectedDoc.id)} target="_blank" rel="noreferrer">Abrir original</a><button className="btn" disabled={busy} onClick={() => void run(() => procurementFiscalControlApi.extractFiscal(selectedDoc.id))}>Extrair dados</button></div><div className="grid md:grid-cols-3 gap-2">{[["invoiceNumber","N.º factura"],["supplierNuit","NUIT fornecedor"],["buyerNuit","NUIT comprador"],["issueDate","Data emissão"],["subtotal","Subtotal"],["vatRate","Taxa IVA (0.16)"],["vatAmount","IVA"],["totalAmount","Total"]].map(([key,label]) => <label key={key} className="text-xs">{label}<input className="input mt-1" type={["subtotal","vatRate","vatAmount","totalAmount"].includes(key)?"number":"text"} value={(facts as any)[key] ?? ""} onChange={(e) => setFacts((current) => ({ ...current, [key]: ["subtotal","vatRate","vatAmount","totalAmount"].includes(key) ? (e.target.value===""?null:Number(e.target.value)) : e.target.value }))}/></label>)}<label className="text-xs">Moeda<select className="input mt-1" value={facts.currency ?? (currency === "USD" ? "USD" : "MZN")} onChange={(e) => setFacts((current) => ({ ...current, currency: e.target.value as "MZN" | "USD" }))}><option value="MZN">MZN</option><option value="USD">USD</option></select></label></div><div className="flex flex-wrap gap-2"><button className="btn" disabled={busy} onClick={() => void run(() => procurementFiscalControlApi.saveFacts(selectedDoc.id,facts))}>Guardar conferência</button>{canApprove && <button className="btn btn-primary" disabled={busy} onClick={() => void run(() => procurementFiscalControlApi.validateFiscal(selectedDoc.id))}>Validar documento fiscal</button>}</div>{selectedDoc.validationSnapshot && <div className={`rounded-lg px-3 py-2 text-xs ${selectedDoc.status==="validado"?"bg-green-50 text-green-800":"bg-amber-50 text-amber-800"}`}><strong>{selectedDoc.status === "validado" ? "Fiscal validado" : "Revisão necessária"}</strong>{selectedDoc.validationSnapshot.hardBlocks?.map((m,i)=><p key={`h${i}`}>• {m}</p>)}{selectedDoc.validationSnapshot.warnings?.map((m,i)=><p key={`w${i}`}>• {m}</p>)}</div>}</>}
    </section>
    <section className="rounded-xl bg-slate-50 p-3 space-y-3"><div><strong className="text-sm">2. Pedidos de pagamento</strong><p className="text-xs text-slate-500">Saldo factura {money(outstanding,currency)} · reservado {money(activeReserved,currency)}</p></div>{hasValidated && ["aprovada","parcialmente_paga"].includes(invoiceStatus) && outstanding>0 && <div className="grid md:grid-cols-4 gap-2 items-end"><label className="text-xs">Valor<input className="input mt-1" type="number" value={amount} onChange={(e)=>setAmount(e.target.value)}/></label><label className="text-xs">Data desejada<input className="input mt-1" type="date" value={paymentDate} onChange={(e)=>setPaymentDate(e.target.value)}/></label><label className="text-xs md:col-span-2">Justificação<input className="input mt-1" value={reason} onChange={(e)=>setReason(e.target.value)}/></label><button className="btn btn-primary" disabled={busy || !(Number(amount)>0) || reason.trim().length<5} onClick={() => void run(async()=>{ const created=await procurementFiscalControlApi.createPaymentRequest(invoiceId,{amount:Number(amount),requestedPaymentDate:paymentDate,reason}); await procurementFiscalControlApi.submitPayment(created.id); })}>Criar e submeter</button></div>}
      {payments.length===0?<p className="text-xs text-slate-500">Sem pedidos.</p>:payments.map((p)=><div key={p.id} className="rounded-lg border bg-white p-3 text-xs"><div className="flex justify-between"><strong>{p.reference} · {money(Number(p.amount),p.currency)}</strong><span>{p.status}</span></div><p className="text-slate-500">{p.reason}</p>{isFinanceAdmin && p.status==="submetido" && <div className="mt-2 flex flex-wrap gap-2"><input className="input max-w-sm" placeholder="Justificação override (só se 1 admin)" value={overrideReason} onChange={(e)=>setOverrideReason(e.target.value)}/><button className="btn btn-primary" onClick={()=>void run(()=>procurementFiscalControlApi.approvePayment(p.id,overrideReason||undefined))}>Aprovar</button><button className="btn" onClick={()=>void run(()=>procurementFiscalControlApi.rejectPayment(p.id,"Pedido não autorizado"))}>Rejeitar</button></div>}{isFinanceAdmin && p.status==="aprovado" && <div className="mt-2 grid md:grid-cols-3 gap-2"><input className="input" placeholder="Referência bancária" value={executionRef} onChange={(e)=>setExecutionRef(e.target.value)}/><input className="input" placeholder="Override se aplicável" value={overrideReason} onChange={(e)=>setOverrideReason(e.target.value)}/><button className="btn btn-primary" onClick={()=>void run(()=>procurementFiscalControlApi.executePayment(p.id,{executionDate:today(),reference:executionRef||undefined,overrideReason:overrideReason||undefined}))}>Executar pagamento</button></div>}{p.status==="executado" && <div className="mt-2 flex gap-2"><span>Executado {p.executionDate} · {p.executionReference ?? "sem referência"}</span><label className="underline cursor-pointer">Anexar comprovativo<input type="file" className="hidden" accept="application/pdf,image/*" onChange={(e)=>{const file=e.target.files?.[0];if(file) void run(()=>procurementFiscalControlApi.uploadPaymentProof(p.id,file));}}/></label>{p.executionProofOriginalName&&<a className="underline" href={procurementFiscalControlApi.paymentProofUrl(p.id)} target="_blank" rel="noreferrer">Ver</a>}</div>}</div>)}
    </section>
    {isFinanceAdmin && <section className="rounded-xl bg-slate-50 p-3 space-y-3"><button className="btn" onClick={async()=>{ const next=!bankOpen; setBankOpen(next); if(next) setBank(await procurementFiscalControlApi.bankReconciliation(projectId)); }}>3. Reconciliação bancária {bankOpen?"▲":"▼"}</button>{bankOpen && <><div className="grid md:grid-cols-[1fr_1fr_auto] gap-2 items-end"><label className="text-xs">Banco<input className="input mt-1" value={bankName} onChange={(e)=>setBankName(e.target.value)}/></label><label className="text-xs">Extracto CSV/XLSX<input type="file" className="input mt-1" accept=".csv,.xlsx" onChange={(e)=>{ const file=e.target.files?.[0]; if(file && bankName.trim()) void run(()=>procurementFiscalControlApi.importBankStatement(projectId,file,{bankName:bankName.trim(),currency})); }}/></label><span className="text-xs text-slate-500">Débitos devem ser negativos.</span></div>{bank?.transactions.map((tx)=><div key={tx.id} className="rounded-lg border bg-white p-3 text-xs"><div className="flex justify-between"><strong>{tx.transactionDate} · {money(Number(tx.amount),tx.currency)}</strong><span>{tx.reference ?? "—"}</span></div><p>{tx.description}</p>{(bank.suggestions.find((s)=>s.transactionId===tx.id)?.matches ?? []).map((m)=><div key={m.paymentRequestId} className="mt-2 flex items-center justify-between rounded bg-green-50 px-2 py-2"><span>{m.score}% · {m.reference} · {m.supplierName} · {m.invoiceNumber}<br/>{m.reasons.join(" · ")}</span><button className="btn btn-primary" onClick={()=>void run(()=>procurementFiscalControlApi.reconcile(tx.id,m.paymentRequestId))}>Reconciliar</button></div>)}<div className="mt-2 flex flex-wrap gap-2"><select className="input max-w-xl" value={manualMatch[tx.id] ?? ""} onChange={(e)=>setManualMatch((current)=>({...current,[tx.id]:e.target.value}))}><option value="">Associar manualmente...</option>{bank.paymentRequests.filter((item)=>Number(tx.amount)<0 && item.request.currency===tx.currency && Math.abs(Math.abs(Number(tx.amount))-Number(item.request.amount))<=0.02).map((item)=><option key={item.request.id} value={item.request.id}>{item.request.reference} · {item.supplierName} · {item.invoiceNumber}</option>)}</select><button className="btn" disabled={!manualMatch[tx.id]} onClick={()=>void run(()=>procurementFiscalControlApi.reconcile(tx.id,manualMatch[tx.id]))}>Reconciliar manual</button><button className="text-slate-500 underline" onClick={()=>void run(()=>procurementFiscalControlApi.ignoreTransaction(tx.id))}>Ignorar movimento</button></div></div>)}</>}</section>}
  </div>;
}
