import { useEffect, useState } from "react";
import { supplierFiscalDocumentsApi, type SupplierFiscalDocument, type SupplierFiscalFacts } from "../api/fiscalDocuments";

export default function SupplierFiscalDocumentPanel({ invoiceId, invoiceCurrency, onChanged }: { invoiceId: string; invoiceCurrency: string; onChanged?: () => void }) {
  const [docs,setDocs]=useState<SupplierFiscalDocument[]>([]); const [selected,setSelected]=useState<string|null>(null); const [facts,setFacts]=useState<SupplierFiscalFacts>({ currency: invoiceCurrency === "USD" ? "USD" : "MZN" }); const [busy,setBusy]=useState(false); const [error,setError]=useState<string|null>(null);
  async function reload(){const rows=await supplierFiscalDocumentsApi.list(invoiceId);setDocs(rows);const d=rows.find(x=>x.id===selected)??rows[0];if(d){setSelected(d.id);setFacts({ currency: invoiceCurrency === "USD" ? "USD" : "MZN", ...(d.reviewedData??d.extractedData??{}) });}}
  useEffect(()=>{void reload().catch(e=>setError(e instanceof Error?e.message:"Erro ao carregar documento fiscal"));},[invoiceId]);
  async function run(task:()=>Promise<unknown>){setBusy(true);setError(null);try{await task();await reload();onChanged?.();}catch(e){setError(e instanceof Error?e.message:"Operação não concluída");}finally{setBusy(false);}}
  const doc=docs.find(d=>d.id===selected)??null; const numeric=new Set(["subtotal","vatRate","vatAmount","totalAmount"]);
  return <div className="card card-pad"><div style={{display:"flex",justifyContent:"space-between",alignItems:"start",gap:"1rem"}}><div><h2 style={{margin:0}}>Documento fiscal</h2><p className="text-muted-sm">Carregue o PDF/imagem original. A empresa valida antes de aprovar a factura.</p></div><label className="btn" style={{cursor:"pointer"}}>Carregar<input type="file" accept="application/pdf,image/*" style={{display:"none"}} onChange={e=>{const f=e.target.files?.[0];if(f) void run(()=>supplierFiscalDocumentsApi.upload(invoiceId,f));}}/></label></div>{error&&<p style={{color:"#b42318"}}>{error}</p>}
    {docs.map(d=><button key={d.id} className="btn" style={{width:"100%",textAlign:"left",marginTop:"0.6rem",justifyContent:"space-between"}} onClick={()=>{setSelected(d.id);setFacts({ currency: invoiceCurrency === "USD" ? "USD" : "MZN", ...(d.reviewedData??d.extractedData??{}) });}}><span>v{d.version} · {d.originalName}</span><span>{d.status.replaceAll("_"," ")}</span></button>)}
    {doc&&<div style={{display:"grid",gap:"0.7rem",marginTop:"1rem"}}><div style={{display:"flex",gap:"0.5rem",flexWrap:"wrap"}}><a className="btn" href={supplierFiscalDocumentsApi.fileUrl(doc.id)} target="_blank" rel="noreferrer">Abrir original</a><button className="btn" disabled={busy} onClick={()=>void run(()=>supplierFiscalDocumentsApi.extract(doc.id))}>Extrair dados</button></div>{doc.extractionMessage&&<p className="text-muted-sm">{doc.extractionMessage}</p>}
      <div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(180px,1fr))",gap:"0.6rem"}}>{[["invoiceNumber","N.º factura"],["supplierNuit","NUIT emitente"],["buyerNuit","NUIT adquirente"],["issueDate","Data emissão"],["subtotal","Subtotal"],["vatRate","Taxa IVA (0.16)"],["vatAmount","IVA"],["totalAmount","Total"]].map(([k,l])=><label key={k} className="text-muted-sm">{l}<input className="input" type={numeric.has(k)?"number":"text"} value={(facts as any)[k]??""} onChange={e=>setFacts(c=>({...c,[k]:numeric.has(k)?(e.target.value===""?null:Number(e.target.value)):e.target.value}))}/></label>)}<label className="text-muted-sm">Moeda<select className="input" value={facts.currency ?? (invoiceCurrency === "USD" ? "USD" : "MZN")} onChange={e=>setFacts(c=>({...c,currency:e.target.value as "MZN"|"USD"}))}><option value="MZN">MZN</option><option value="USD">USD</option></select></label></div><button className="btn btn-primary" disabled={busy} onClick={()=>void run(()=>supplierFiscalDocumentsApi.saveFacts(doc.id,facts))}>Guardar dados do documento</button>{doc.status==="validado"&&<p style={{color:"#067647"}}><strong>Documento fiscal validado pela empresa.</strong></p>}{doc.status==="rejeitado"&&<p style={{color:"#b42318"}}>Documento rejeitado: {doc.rejectionReason}</p>}</div>}
  </div>;
}
