import { useEffect, useState } from "react";
import { Link, useNavigate, useParams } from "react-router-dom";
import { AppShell } from "../components/AppShell";
import { supplierPortalAuthApi, type SupplierAccount } from "../api/supplierPortal";
import { supplierAccountsPayableApi, type SupplierInvoice } from "../api/accountsPayable";
import SupplierFiscalDocumentPanel from "../components/SupplierFiscalDocumentPanel";

function money(value: number, currency: string) { return new Intl.NumberFormat("pt-MZ", { style: "currency", currency, maximumFractionDigits: 2 }).format(value); }
function today() { return new Date().toISOString().slice(0, 10); }

export default function SupplierInvoiceDetailPage() {
  const { id } = useParams<{ id: string }>(); const navigate = useNavigate();
  const [account, setAccount] = useState<SupplierAccount | null>(null); const [invoice, setInvoice] = useState<SupplierInvoice | null>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null);
  const [creditOpen, setCreditOpen] = useState(false); const [creditNumber, setCreditNumber] = useState(""); const [creditAmount, setCreditAmount] = useState(""); const [creditReason, setCreditReason] = useState(""); const [saving, setSaving] = useState(false);
  async function reload() { if (id) setInvoice(await supplierAccountsPayableApi.invoice(id)); }
  useEffect(() => { supplierPortalAuthApi.me().then(async (me) => { setAccount(me); await reload(); }).catch(() => navigate("/login", { replace: true })).finally(() => setLoading(false)); }, [id, navigate]);
  async function createCredit() { if (!invoice) return; setSaving(true); setError(null); try { await supplierAccountsPayableApi.createCreditNote(invoice.id, { creditNumber, issueDate: today(), amount: Number(creditAmount), reason: creditReason }); setCreditOpen(false); setCreditNumber(""); setCreditAmount(""); setCreditReason(""); await reload(); } catch (cause) { setError(cause instanceof Error ? cause.message : "Não foi possível submeter a nota de crédito"); } finally { setSaving(false); } }
  if (loading || !account) return <AppShell accountName={account?.name ?? "…"}><main className="portal-main"><div className="skeleton" style={{ height: "15rem" }}/></main></AppShell>;
  if (!invoice) return <AppShell accountName={account.name}><main className="portal-main"><div className="card card-pad">Factura não encontrada.</div></main></AppShell>;
  return <AppShell accountName={account.name}><main className="portal-main"><Link to="/facturas" className="text-muted-sm">← Facturas</Link><section className="hero-panel fade-up"><div className="hero-panel-content"><p className="hero-eyebrow">{invoice.companyName} · {invoice.projectName}</p><h1 className="hero-title">{invoice.invoiceNumber}</h1><p className="hero-subtitle">{invoice.status.replaceAll("_", " ")} · Match: {invoice.matchStatus}</p></div></section>{error && <div className="card card-pad" style={{ color: "#b42318" }}>{error}</div>}
    <div className="card card-pad"><div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit,minmax(150px,1fr))", gap: "1rem" }}><div><span className="text-muted-sm">Total</span><br/><strong>{money(Number(invoice.totalAmount), invoice.currency)}</strong></div><div><span className="text-muted-sm">Créditos</span><br/><strong>{money(invoice.balance.credited, invoice.currency)}</strong></div><div><span className="text-muted-sm">Pago</span><br/><strong>{money(invoice.balance.paid, invoice.currency)}</strong></div><div><span className="text-muted-sm">Em aberto</span><br/><strong>{money(invoice.balance.outstanding, invoice.currency)}</strong></div></div>{invoice.rejectionReason && <p style={{ color: "#b42318" }}>Motivo de rejeição: {invoice.rejectionReason}</p>}</div>
    <SupplierFiscalDocumentPanel invoiceId={invoice.id} invoiceCurrency={invoice.currency} onChanged={() => void reload()} />
    <div className="card"><div className="card-header"><h2>Linhas</h2></div>{(invoice.lines ?? []).map((line) => <div key={line.id} style={{ padding: "0.9rem 1.25rem", borderTop: "1px solid var(--border)", display: "flex", justifyContent: "space-between", gap: "1rem" }}><div><strong>{line.materialName}</strong><p className="text-muted-sm">{Number(line.quantity).toLocaleString("pt-MZ")} × {money(Number(line.unitCost), invoice.currency)}</p></div><strong>{money(Number(line.lineTotal), invoice.currency)}</strong></div>)}</div>
    {["aprovada", "parcialmente_paga", "paga"].includes(invoice.status) && <div className="card card-pad"><div style={{ display: "flex", justifyContent: "space-between", alignItems: "center" }}><div><h2 style={{ margin: 0 }}>Notas de crédito</h2><p className="text-muted-sm">Use quando existir desconto, devolução ou regularização aceite.</p></div><button className="btn" onClick={() => setCreditOpen((value) => !value)}>Nova nota de crédito</button></div>{creditOpen && <div style={{ display: "grid", gap: "0.6rem", marginTop: "1rem" }}><input className="input" placeholder="Número da nota" value={creditNumber} onChange={(e) => setCreditNumber(e.target.value)}/><input type="number" className="input" placeholder="Valor" value={creditAmount} onChange={(e) => setCreditAmount(e.target.value)}/><textarea className="input" rows={2} placeholder="Motivo" value={creditReason} onChange={(e) => setCreditReason(e.target.value)}/><button className="btn btn-primary" disabled={saving || !creditNumber || !(Number(creditAmount) > 0) || creditReason.trim().length < 5} onClick={createCredit}>Submeter</button></div>}{(invoice.creditNotes ?? []).map((credit) => <div key={credit.id} style={{ padding: "0.8rem 0", borderTop: "1px solid var(--border)" }}><strong>{credit.creditNumber} · {money(Number(credit.amount), invoice.currency)}</strong><p className="text-muted-sm">{credit.status} · {credit.reason}</p></div>)}</div>}
  </main></AppShell>;
}
